spring:
  application:
    name: cooking

  datasource:
    url: ${DBURL}
    username: ${DBUSER}
    password: ${DBPASSWORD}

  jpa:
    hibernate:
      ddl-auto: "none"
    show-sql: true
  flyway:
    enabled: true
