spring:
  application:
    name: cooking
  devtools:
    add-properties: false
    livereload:
      enabled: false

  datasource:
    url: ${DBURL}
    username: ${DBUSER}
    password: ${DBPASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

  flyway:
    enabled: true
