spring:
  application:
    name: cooking-roulette-recipes
  mvc:
    apiversion:
      default: 1.0
      detect-supported: true
      use:
        path-segment: 1
  jpa:
    hibernate:
      ddl-auto: "none"
