CREATE TABLE IF NOT EXISTS recipe
(
    cook_time REAL NOT NULL,
    id        UUID NOT NULL,
    name      VARCHAR(255),
    CONSTRAINT PK_RECIPE
        PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS recipe_ingredient
(
    weight          REAL,
    id              UUID NOT NULL,
    recipe_id       UUID,
    ingredient_name VARCHAR(255),
    ingredient_type VARCHAR(255),
    CONSTRAINT PK_RECIPEINGREDIENT
        PRIMARY KEY (id),
    CONSTRAINT FK_RECIPEINGREDIENT_ON_RECIPE
        FOREIGN KEY (recipe_id) REFERENCES recipe,
    CONSTRAINT RECIPE_INGREDIENT_INGREDIENT_TYPE_CHECK
        CHECK ((ingredient_type)::TEXT = ANY
               ((ARRAY ['CARNES'::CHARACTER VARYING, 'CEREALES_Y_TUBERCULOS'::CHARACTER VARYING, 'GRASAS'::CHARACTER VARYING, 'VERDURAS'::CHARACTER VARYING, 'FRUTAS'::CHARACTER VARYING, 'LECHE'::CHARACTER VARYING, 'LEGUMINOSAS'::CHARACTER VARYING, 'AZUCARES'::CHARACTER VARYING, 'ALIMENTOS_LIBRES_DE_ENERGIA'::CHARACTER VARYING, 'CEREALES_CON_GRASA'::CHARACTER VARYING, 'GRASAS_CON_AZUCAR'::CHARACTER VARYING])::TEXT[]))
);

CREATE TABLE IF NOT EXISTS recipe_step
(
    step_number      INTEGER NOT NULL,
    id               UUID    NOT NULL,
    recipe_id        UUID,
    step_instruction VARCHAR(255),
    CONSTRAINT PK_RECIPESTEP
        PRIMARY KEY (id),
    CONSTRAINT FK_RECIPESTEP_ON_RECIPE
        FOREIGN KEY (recipe_id) REFERENCES recipe
);
